sudo: false
language: python

matrix:
  include:
    - python: 3.6
    - python: 3.5
    - python: 2.7
    - python: pypy
    - python: pypy3

install:
  - pip install .
  - pip install pytest
  - pip list

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - cd tests
  - py.test
